name: deploy-expiration
on:
  push:
    branches: 
      - master
    paths:
      - 'expiration/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t yousuf85/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yousuf85/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ecommerce-app
      - run: kubectl rollout restart deployment expiration-depl